apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: streampulse-prometheus
    access: proxy
    url: http://streampulse-prometheus:9090
    isDefault: true
    editable: false
